### ISSUE TITLE
Maintaining `node-cmark-gfm` and `electron-markdown`

### ISSUE THREAD

**Issue by HashimotoYT** [BinaryMuse/node-cmark-gfm#16]
Hello @BinaryMuse! Thanks for creating these good modules and adopted into Electron Website.

I noticed this module is broken when installing from zero. And I want to know if you plan to maintain these modules since these modules it's an important part of website infrastructure, as they create the blog posts beautiful.

Also, I would like to continue to maintain these modules in a good state, keeping them updated, bug fixed.

Thanks for working on it 🙌. /cc @BinaryMuse

**Comment by mvasilkov** [comment]
@HashimotoYT I'm currently working on the same thing really. While I've never had a chance to discuss it with Michelle @BinaryMuse, I went on to fork the repo, update dependencies, fix the build and some such. My branch is available here: https://github.com/mvasilkov/cmark-gfm

I would love to join forces, if possible.

**Comment by BinaryMuse** [comment]
@HashimotoYT sorry for the delayed response! Since I'm not working on Electron these days I don't have a lot of info about how this is used and when it needs updated, but I'd be happy to give write access to the repo and the npm module if you wanted to keep it going! (ofc I'm also totally fine with a fork :)

**Comment by HashimotoYT** [comment]
Since I do not very love forking without upstreaming changes, having write access to be finer for future using. I just take some free time to give for updating and maintaining these modules for Electron.

**Comment by BinaryMuse** [comment]
@HashimotoYT I added you as a collaborator on both repos. Once you accept I'll set the permissions. Can you let me know your npm handle?

**Comment by BinaryMuse** [comment]
Oops I found you, I was just searching wrong 🙈

**Comment by HashimotoYT** [comment]
NPM `hashimoto`. Invites accepted.

**Comment by BinaryMuse** [comment]
Alright, all should be set up. Let me know if you run into any issues <3

**Comment by mvasilkov** [comment]
May I also have the access? I've done some work on upgrading things on my branch, would love to push it upstream too. (Some of this is in my pull request, but not all.)

**Comment by BinaryMuse** [comment]
@mvasilkov I will leave these sorts of decisions up to @HashimotoYT. I granted access quickly to him only because I know him and have worked with him in the past on this and related projects.

**Comment by HashimotoYT** [comment]
Thanks, I close that problem when check everything.

@mvasilkov Most optimal here it's fork the repo and open PR, after review, I publish these changes.

**Comment by mvasilkov** [comment]
> @mvasilkov I will leave these sorts of decisions up to @HashimotoYT. I granted access quickly to him only because I know him and have worked with him in the past on this and related projects.

Ah, got it. Okay then.
